apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-replica-service
spec:
  type: NodePort
  selector:
    app: myapp2
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31232
