apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp2

  template:
    metadata:
      name: myapp2-pod
      labels:
        app: myapp2
    spec:
      containers:
        - name: myapp2-cont
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
