apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: myapp
  template:
    metadata:
      name: my-app-pod
      labels: 
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: stacksimplify/kubenginx:3.0.0
          ports:
            - containerPort: 80
            